/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignalsRouteImport } from './routes/_app/signals'
import { Route as AppScannerRouteImport } from './routes/_app/scanner'
import { Route as AppEaBridgeRouteImport } from './routes/_app/ea-bridge'
import { Route as AppEaRouteImport } from './routes/_app/ea'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as ApiPublicEaTradeReportRouteImport } from './routes/api/public/ea/trade-report'
import { Route as ApiPublicEaHeartbeatRouteImport } from './routes/api/public/ea/heartbeat'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppEaBridgeRoute = AppEaBridgeRouteImport.update({
  id: '/ea-bridge',
  path: '/ea-bridge',
  getParentRoute: () => AppRoute,
} as any)
const AppEaRoute = AppEaRouteImport.update({
  id: '/ea',
  path: '/ea',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicEaTradeReportRoute = ApiPublicEaTradeReportRouteImport.update({
  id: '/api/public/ea/trade-report',
  path: '/api/public/ea/trade-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEaHeartbeatRoute = ApiPublicEaHeartbeatRouteImport.update({
  id: '/api/public/ea/heartbeat',
  path: '/api/public/ea/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/calendar': typeof AppCalendarRoute
  '/ea': typeof AppEaRoute
  '/ea-bridge': typeof AppEaBridgeRoute
  '/scanner': typeof AppScannerRoute
  '/signals': typeof AppSignalsRoute
  '/api/public/ea/heartbeat': typeof ApiPublicEaHeartbeatRoute
  '/api/public/ea/trade-report': typeof ApiPublicEaTradeReportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/calendar': typeof AppCalendarRoute
  '/ea': typeof AppEaRoute
  '/ea-bridge': typeof AppEaBridgeRoute
  '/scanner': typeof AppScannerRoute
  '/signals': typeof AppSignalsRoute
  '/': typeof AppIndexRoute
  '/api/public/ea/heartbeat': typeof ApiPublicEaHeartbeatRoute
  '/api/public/ea/trade-report': typeof ApiPublicEaTradeReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/ea': typeof AppEaRoute
  '/_app/ea-bridge': typeof AppEaBridgeRoute
  '/_app/scanner': typeof AppScannerRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/ea/heartbeat': typeof ApiPublicEaHeartbeatRoute
  '/api/public/ea/trade-report': typeof ApiPublicEaTradeReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plans'
    | '/register'
    | '/account'
    | '/admin'
    | '/calendar'
    | '/ea'
    | '/ea-bridge'
    | '/scanner'
    | '/signals'
    | '/api/public/ea/heartbeat'
    | '/api/public/ea/trade-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/plans'
    | '/register'
    | '/account'
    | '/admin'
    | '/calendar'
    | '/ea'
    | '/ea-bridge'
    | '/scanner'
    | '/signals'
    | '/'
    | '/api/public/ea/heartbeat'
    | '/api/public/ea/trade-report'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/plans'
    | '/register'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/calendar'
    | '/_app/ea'
    | '/_app/ea-bridge'
    | '/_app/scanner'
    | '/_app/signals'
    | '/_app/'
    | '/api/public/ea/heartbeat'
    | '/api/public/ea/trade-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicEaHeartbeatRoute: typeof ApiPublicEaHeartbeatRoute
  ApiPublicEaTradeReportRoute: typeof ApiPublicEaTradeReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scanner': {
      id: '/_app/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ea-bridge': {
      id: '/_app/ea-bridge'
      path: '/ea-bridge'
      fullPath: '/ea-bridge'
      preLoaderRoute: typeof AppEaBridgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ea': {
      id: '/_app/ea'
      path: '/ea'
      fullPath: '/ea'
      preLoaderRoute: typeof AppEaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/ea/trade-report': {
      id: '/api/public/ea/trade-report'
      path: '/api/public/ea/trade-report'
      fullPath: '/api/public/ea/trade-report'
      preLoaderRoute: typeof ApiPublicEaTradeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ea/heartbeat': {
      id: '/api/public/ea/heartbeat'
      path: '/api/public/ea/heartbeat'
      fullPath: '/api/public/ea/heartbeat'
      preLoaderRoute: typeof ApiPublicEaHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppEaRoute: typeof AppEaRoute
  AppEaBridgeRoute: typeof AppEaBridgeRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppEaRoute: AppEaRoute,
  AppEaBridgeRoute: AppEaBridgeRoute,
  AppScannerRoute: AppScannerRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicEaHeartbeatRoute: ApiPublicEaHeartbeatRoute,
  ApiPublicEaTradeReportRoute: ApiPublicEaTradeReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
